builtins = [
# micropython
    "micropython",
    "const",
    "ptr8",
    "ptr32",

# picovector
    "algorithm",
    "brush",
    "color",
    "font",
    "image",
    "mat3",
    "pen",
    "pixel_font",
    "vec2",
    "rect",
    "shape",
    "screen",

# badgeware.py
    "display",
    "launch",
    "run",
    "loop",
    "reset",
    "fatal_error",
    "wait_for_button_or_alarm",

# math.py
    "clamp",
    "rnd",
    "frnd",

# text.py
    "rom_font",
    "load_font",
    "text",

# sprite.py
    "SpriteSheet",
    "AnimatedSprite",

# filesystem.py
    "file_exists",
    "is_dir",

# rtc.py
    "rtc",

# state.py
    "State",

# badge.py
    "badge",
    "HIRES",
    "LORES",
    "VSYNC",
    "FAST_UPDATE",
    "FULL_UPDATE",
    "MEDIUM_UPDATE",
    "DITHER",
    "BUTTON_A",
    "BUTTON_B",
    "BUTTON_C",
    "BUTTON_UP",
    "BUTTON_DOWN",
    "BUTTON_HOME"
]

# Include:
# F = Pyflakes
# Q = Quotes
# E/W = pycodestyle (Whitespace, Line lengths etc)
# B - flake8-bugbear = Unused loop variables, sloppy code
# COM - flake8-commas
# BLE - flake8-blind-except
# C4  - flake8-comprehensions
# ISC - flake8-implicit-str-concat = Implicit string concat, eg: `"hello" "world"` on one line
# ICN - flake8-import-conventions = Import conventions
# PIE - flake8-pie = Misc silliness, catches range with a 0 start argument
# RET - flake8-return = Enforces straight-forward code around return statements
# SLF - flake8-self
# ARG - flake8-unused-arguments

lint.select = [
    "F",
    "Q",
    "W",
    "E",
    "B",
    "COM",
    "BLE",
    "C4",
    "ISC",
    "ICN",
    "PIE",
    "RSE",
    "RET",
    "SLF",
    "ARG"
]

# Ignore:
# E501 - "line too long". How narrow is your screen!?
# E402 - "module level import not at top of file". Needs must!
# COM812 - "Add trailing comma". These are a little obnoxious and weird.
# ICN001 - "numpy should be imported as np". No. No it should not.

lint.ignore = [
    "E501",
    "E402",
    "COM812",
    "ICN001"
]
