name: MicroPython

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: MicroPython ${{ matrix.name }}
    runs-on: ubuntu-24.04
    continue-on-error: true
    strategy:
      matrix:
        include:
        - name: badger

    env:
      # MicroPython version will be contained in github.event.release.tag_name for releases
      CI_RELEASE_FILENAME: ${{ matrix.name }}-${{ github.event.release.tag_name || github.sha }}-micropython
      CI_PROJECT_ROOT: ${{ github.workspace }}/src-${{ github.sha }}
      CI_BUILD_ROOT: ${{ github.workspace }}
      CI_USE_ENV: 1

    steps:
    - name: Compiler Cache Fixup
      run: |
        mkdir -p /home/runner/.ccache
  
    - name: "CCache: Restore saved cache"
      uses: actions/cache@v4
      with:
        path: /home/runner/.ccache
        key: ccache-micropython-${{ matrix.name }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ccache-micropython-${{ matrix.name }}-${{ github.ref }}
          ccache-micropython-${{ matrix.name }}-

    - name: "Checkout Project"
      uses: actions/checkout@v4
      with:
        submodules: true
        path: ${{ env.CI_PROJECT_ROOT }}

    - name: "Prepare All: Generate cache key"
      shell: bash
      run: |
        echo "CI_CACHE_KEY=`shasum "$CI_PROJECT_ROOT/ci/micropython.sh" | cut -d " " -f 1`" >> $GITHUB_ENV

    - name: "Prepare All: Restore saved cache"
      id: cache-prepare-all
      uses: actions/cache@v4
      with:
        path: ${{ env.CI_BUILD_ROOT }}
        key: prepare-all-${{ env.CI_CACHE_KEY }}
        restore-keys: |
          prepare-all-${{ env.CI_CACHE_KEY }}

    - name: "Install Arm GNU Toolchain (arm-none-eabi-gcc)"
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '13.3.Rel1'

    - name: "Prepare All: Install dependencies"
      if: steps.cache-prepare-all.outputs.cache-hit == 'true'
      shell: bash
      run: |
        source $CI_PROJECT_ROOT/ci/micropython.sh
        ci_install_build_deps

    - name: "Prepare All: Prepare tools & dependencies"
      if: steps.cache-prepare-all.outputs.cache-hit != 'true'
      shell: bash
      run: |
        source $CI_PROJECT_ROOT/ci/micropython.sh
        mkdir -p $CI_BUILD_ROOT
        ci_install_build_deps
        ci_prepare_all

    - name: "MicroPython: Configure"
      shell: bash
      run: |
        source $CI_PROJECT_ROOT/ci/micropython.sh
        micropython_version
        ci_cmake_configure

    - name: "MicroPython: Build"
      shell: bash
      run: |
        source $CI_PROJECT_ROOT/ci/micropython.sh
        ci_cmake_build

    - name: "Artifacts: Upload .uf2"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.CI_RELEASE_FILENAME }}.uf2
        path: ${{ env.CI_BUILD_ROOT }}/${{ env.CI_RELEASE_FILENAME }}.uf2
        
    - name: "Artifacts: Upload .uf2 (With Filesystem)"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.CI_RELEASE_FILENAME }}-with-filesystem.uf2
        path: ${{ env.CI_BUILD_ROOT }}/${{ env.CI_RELEASE_FILENAME }}-with-filesystem.uf2

    - name: "Release: Upload .uf2"
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.CI_BUILD_ROOT }}/${{ env.CI_RELEASE_FILENAME }}.uf2

    - name: "Release: Upload .uf2 (With Filesystem)"
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.CI_BUILD_ROOT }}/${{ env.CI_RELEASE_FILENAME }}-with-filesystem.uf2